
name: android

on:
  push:
    branches: [ main ,v3.0.0]
  pull_request:
    branches: [ main ,v3.0.0]

jobs:
  build_android:
    name: Build Android（Mobile）
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: ./SampleCode/Android

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
  
